version: '3'
services:
  influxdb:
    image: influxdb:1.8
    volumes:
      - ./influxdb/data:/var/lib/influxdb
      - ./influxdb/config/:/etc/influxdb/
    ports:
      - "8086:8086"
      - "8082:8082"
      - "8089:8089"

  telegraf:
    image: telegraf:1.14
    volumes:
      - ./telegraf/:/etc/telegraf/
      # for monitoring docker containers on the host
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - influxdb

  kapacitor:
    image: kapacitor:1.5
    volumes:
      - ./kapacitor/data/:/var/lib/kapacitor
      - ./kapacitor/config/:/etc/kapacitor/
    ports:
      - "9092:9092"
    depends_on:
      - influxdb

  chronograf:
    image: chronograf:1.8
    volumes:
      - ./chronograf/data/:/var/lib/chronograf/
    ports:
      - "8888:8888"
    depends_on:
      - kapacitor
      - influxdb
      - telegraf